# Generated by Django 3.2.8 on 2021-11-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена авто'),
        ),
    ]
